version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: '/var/lib/postgresql/data/pgdata'
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres

  backend:
    container_name: backend
    restart: always
    build:
      target: development
    command: pnpm run start:dev
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST=database
    volumes:
      - .:/usr/src/app
      - node_modules_data:/usr/src/app/node_modules
    networks:
      - postgres
    depends_on:
      - database

volumes:
  postgres_data:
  node_modules_data:

networks:
  postgres:
    driver: bridge
