FROM node:18

ENV NODE_ENV production

WORKDIR /usr/src/app

COPY . .

RUN npm i -g pnpm  

RUN pnpm install -P

RUN pnpm run prisma:generate
RUN pnpm run back:build


CMD [ "pnpm", "run", "back:start" ]