version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - backend

  database_test:
    image: postgres:latest
    container_name: database_test
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5433:5432

  backend:
    container_name: backend
    restart: always
    build:
      dockerfile: ./Dockerfile.backend
    command: pnpm run start:dev
    ports:
      - 3333:3333
    volumes:
      - backend_data:/usr/src/app
    depends_on:
      - postgres
    networks:
      - backend

  # frontend:
  #   build:
  #     dockerfile: ./Dockerfile.frontend
  #   container_name: frontend
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - frontend_data:/app
  #   env_file: ./frontend/.env.prod
  #   depends_on:
  #     - backend

volumes:
  postgres:
  redis_data:
  backend_data:
  frontend_data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
