version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: '/var/lib/postgresql/data/pgdata'
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres

  test_database:
    image: postgres:latest
    container_name: test_database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: '/var/lib/postgresql/data/pgdata'
    ports:
      - 5433:5432
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - postgres

volumes:
  postgres_data:
  postgres_test_data:

networks:
  postgres:
    driver: bridge
